install.packages('logger')
install.packages('SoupX', version='1.6.1')
install.packages('sctransform', version='0.3.3')
install.packages('glmpca', version='0.2.0')
install.packages('scran', version='0.2.0')
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("scran")
if (!require("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("bowang-lab/simATAC")